# Generated by Django 5.0.3 on 2024-04-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUs', '0002_contactus_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='content',
            new_name='message',
        ),
    ]
